# Generated by Django 6.0.6 on 2026-06-05 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sirket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=120, unique=True, verbose_name='Şirket ismi')),
                ('logo', models.ImageField(blank=True, upload_to='sirket_logolari/', verbose_name='Logo')),
                ('aciklama', models.TextField(blank=True, verbose_name='Kısa açıklama')),
                ('yayinda', models.BooleanField(default=False, verbose_name='Ana sayfada yayınla')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
                'ordering': ['isim'],
            },
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=160, verbose_name='Ürün ismi')),
                ('fotograf', models.ImageField(blank=True, upload_to='urun_fotograflari/', verbose_name='Ürün fotoğrafı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('kargonun_gelecegi_yer', models.CharField(max_length=180, verbose_name='Kargonun geleceği yer')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('yayinda', models.BooleanField(default=True, verbose_name='Ürünü göster')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('sirket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urunler', to='kargo.sirket', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['-olusturulma_tarihi'],
            },
        ),
    ]
