# Generated by Django 6.0.6 on 2026-06-05 16:42

from django.db import migrations, models
from django.utils.text import slugify


def sirket_sluglarini_doldur(apps, schema_editor):
    Sirket = apps.get_model('kargo', 'Sirket')
    kullanilanlar = set(
        Sirket.objects.exclude(slug__isnull=True).exclude(slug='').values_list('slug', flat=True)
    )

    for sirket in Sirket.objects.filter(slug__isnull=True):
        base_slug = slugify(sirket.isim) or f'sirket-{sirket.pk}'
        slug = base_slug
        counter = 2
        while slug in kullanilanlar:
            slug = f'{base_slug}-{counter}'
            counter += 1
        sirket.slug = slug
        sirket.save(update_fields=['slug'])
        kullanilanlar.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True, verbose_name='Endpoint'),
        ),
        migrations.RunPython(sirket_sluglarini_doldur, migrations.RunPython.noop),
    ]
