# Generated by Django 6.0.6 on 2026-06-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0002_sirket_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='adet',
            field=models.PositiveIntegerField(default=1, verbose_name='Adet'),
        ),
        migrations.AddField(
            model_name='urun',
            name='cikis_yeri',
            field=models.CharField(blank=True, max_length=180, verbose_name='Çıkış yeri'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kargo_durumu',
            field=models.CharField(choices=[('hazirlaniyor', 'Hazırlanıyor'), ('yolda', 'Yolda'), ('kibrista', 'Kıbrıs’ta'), ('teslime_hazir', 'Teslime hazır'), ('teslim_edildi', 'Teslim edildi'), ('gecikti', 'Gecikti')], default='hazirlaniyor', max_length=24, verbose_name='Kargo durumu'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kargo_notu',
            field=models.TextField(blank=True, verbose_name='Kargo notu'),
        ),
        migrations.AddField(
            model_name='urun',
            name='paket_agirligi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Paket ağırlığı (kg)'),
        ),
        migrations.AddField(
            model_name='urun',
            name='siparis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Sipariş tarihi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='tahmini_gelis_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Tahmini geliş tarihi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='takip_kodu',
            field=models.CharField(blank=True, max_length=120, verbose_name='Takip kodu'),
        ),
    ]
