# Generated by Django 6.0.6 on 2026-06-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0003_urun_adet_urun_cikis_yeri_urun_kargo_durumu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='kargo_durumu',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='kargo_notu',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='paket_agirligi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='siparis_tarihi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='tahmini_gelis_tarihi',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='takip_kodu',
        ),
    ]
