# Generated by Django 6.0.6 on 2026-06-07 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0004_remove_urun_kargo_durumu_remove_urun_kargo_notu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sirket',
            name='sahip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sirketleri', to=settings.AUTH_USER_MODEL, verbose_name='Şirket sahibi'),
        ),
        migrations.AddField(
            model_name='urun',
            name='kategori',
            field=models.CharField(blank=True, max_length=80, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='urun',
            name='ozellikler',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ek özellikler'),
        ),
        migrations.CreateModel(
            name='SaticiYetkisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Satıcı e-postası')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('veren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verdigi_satici_yetkileri', to=settings.AUTH_USER_MODEL, verbose_name='Yetkiyi veren')),
            ],
            options={
                'verbose_name': 'Satıcı yetkisi',
                'verbose_name_plural': 'Satıcı yetkileri',
                'ordering': ['email'],
            },
        ),
    ]
