# Generated by Django 6.0.6 on 2026-06-07 21:30

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def varsayilan_kategorileri_ekle(apps, schema_editor):
    SirketKategorisi = apps.get_model('kargo', 'SirketKategorisi')
    kategoriler = [
        ('Moda', 'Giyim, ayakkabı ve aksesuar satan işletmeler.'),
        ('Teknoloji', 'Elektronik, bilgisayar, telefon ve aksesuar ürünleri.'),
        ('Ev ve Yaşam', 'Ev, dekorasyon, mutfak ve yaşam ürünleri.'),
        ('Kozmetik', 'Bakım, kozmetik ve kişisel ürünler.'),
        ('Market', 'Gıda, temel ihtiyaç ve günlük tüketim ürünleri.'),
        ('Spor', 'Spor ekipmanları, outdoor ve hobi ürünleri.'),
        ('Kitap ve Kırtasiye', 'Kitap, kırtasiye ve eğitim ürünleri.'),
        ('Diğer', 'Özel veya karma ürün satan işletmeler.'),
    ]
    for sira, (ad, aciklama) in enumerate(kategoriler, start=10):
        SirketKategorisi.objects.get_or_create(
            ad=ad,
            defaults={
                'slug': slugify(ad),
                'aciklama': aciklama,
                'sira': sira,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0005_sirket_sahip_urun_kategori_urun_ozellikler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SirketKategorisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=80, unique=True, verbose_name='Kategori adı')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='Kategori endpointi')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveIntegerField(default=100, verbose_name='Sıra')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Şirket kategorisi',
                'verbose_name_plural': 'Şirket kategorileri',
                'ordering': ['sira', 'ad'],
            },
        ),
        migrations.AddField(
            model_name='sirket',
            name='iletisim_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='İletişim e-postası'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='isletme_tipi',
            field=models.CharField(blank=True, max_length=120, verbose_name='İşletme tipi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='merkez',
            field=models.CharField(blank=True, max_length=160, verbose_name='Merkez / şehir'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='ozel_kategori',
            field=models.CharField(blank=True, max_length=80, verbose_name='Özel kategori'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='telefon',
            field=models.CharField(blank=True, max_length=40, verbose_name='Telefon'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='teslimat_bolgeleri',
            field=models.TextField(blank=True, verbose_name='Teslimat bölgeleri'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='web_sitesi',
            field=models.URLField(blank=True, verbose_name='Web sitesi'),
        ),
        migrations.AddField(
            model_name='sirket',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sirketler', to='kargo.sirketkategorisi', verbose_name='Şirket kategorisi'),
        ),
        migrations.RunPython(varsayilan_kategorileri_ekle, migrations.RunPython.noop),
    ]
