# Generated by Django 6.0.6 on 2026-06-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0006_sirketkategorisi_sirket_iletisim_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sirket',
            name='kategori',
        ),
        migrations.AddField(
            model_name='sirket',
            name='kategoriler',
            field=models.ManyToManyField(blank=True, related_name='sirketler', to='kargo.sirketkategorisi', verbose_name='Şirket kategorileri'),
        ),
        migrations.AlterField(
            model_name='sirket',
            name='ozel_kategori',
            field=models.CharField(blank=True, max_length=240, verbose_name='Özel kategoriler'),
        ),
    ]
