# Generated by Django 6.0.6 on 2026-06-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kargo', '0007_remove_sirket_kategori_sirket_kategoriler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='vergi_orani',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vergi oranı (%)'),
        ),
    ]
